language: node_js
cache:
  yarn: true
  directories:
  - "node_modules"
notifications:
  email: false
node_js:
- stable
os:
- linux
addons:
  chrome: stable
  apt:
    sources:
    - key_url: "https://dl.yarnpkg.com/debian/pubkey.gpg"
    - sourceline: "deb https://dl.yarnpkg.com/debian/ stable main"
    packages:
    - yarn
install:
- yarn config list
- yarn
script:
- set -e
- yarn run build
- yarn run test
- yarn run apidoc
- set +e
after_success:
- chmod ugo+x ./deploy.sh
- "./deploy.sh"
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: LdQr1FTRbiLboL5DQsJ31ngiIqJDC8gAwKzUVCzv3G/tcLFokwmGJUB5pEpvSgmbWVhNEqqqNwymj+7ib2ylx4QiNVDFWqRSZ+if9mFoCiTmvrJeKxmxOs0aPZtsb5sYHQqf5XLj59275PH43PO9zpJSfiOdekm924pEOqUa24vI4LnGRMDcgmWd77QURbLCOIOXkfWH15TahvTqb7Z8C5pNB5Qt5jlsd8/iPCFriZrCcEFaMtd3psKjsTsQEpyG3kAHAsbQbbK8hc1tF7mol9sypvKRWpUvrpR4JUBNSLnLgposzHF1LD4ycKoqI0/o1iogo7CQbxJ/QFwbzE2DbM4T9J6A5mt426ydT3nByBt04nlcnIgvv0OXZmlmT/Aqhk6xBtNm9c676oqJ6+q3seQoNpgnFxeCWyi7rtJnQQTglWoMTxCoPpE2gipvZ+U/IfUYi5pxz78AcvVHAGPVTto3mwYuzPHEBeq9ecbKDtaPnMOSh96/z65LGhXrn2N9vTVRqnYq4h2cpgPwRGLn2S6HX9o8Lq3MuHU/PUg7gShnjKx0rjC94/g/5IXX0mzOboNEig4OrLK/J2Z+X3T+J2o61dKMtF3ixXDDMWZGeT+KiEfMxP0ivuaIYXCG2ukCI3XYt0Kn8NLQI/6yKUVWsB8DMPkbZVvrfeoxZ9N7Rh8=
  - secure: XOgQe/+iYJL9j1koxqWf3fWXagbK0YGy41fQQx7a8hR4zoLMGVBlQOVT+5Ut26cAkY38aGqjfrGP+o1xPexnca4qMZ1i8IpjhCD8PhFzktmWy9K3e+xl0PRXhIrlMhrwas7q24qBHvQeqpvFsvbX2DbtegM4+fgQiE3ckqNon8rwfc4BfhOgxIWmcoZaI66WsYZ7uaD6En1JUaQ7oD3m7C1xG8tAlNxOEmY9jLKHWCpW9V+tvb6qiZnXOPzyO3C1d6Wb4hBYxwVq5yh5odKEMXU8mv9QgAIu0PafA5860eKqt68dGeyhA3cM8oDyWYBU++nyb8n2fvdLKFOKmd2MooCb9N7h94J4a/lX1dfY5eU5rUgmodbEetd8f7Dxh2ChHetKnfxvKkxLOCkwPivWGBcSkL3vQcbCFMKWktLuU0SqRE0NhXzFdB+Q+jG4d3zm5S8bx41BCbkbyyw94Nrmn7BknnLIuLecqczj4n6jLYA7ahJ4J8/mMRTi+puyeCaV5tqaIPRkYM36E4lpYf9eQotSeMf/GGz1O+TkUfCDT+PWm7UyjbTCw6v5yJlZBe071ynD3jcwtSDrO9IlxhE42/P78McSnhunOYQB+rJqZyICzF3ul26sk+d1yWkL9Xf5Xu0IF4A+VXmD8e5bO2354W2JBAo8EEwEg2IOwWviWHM=
  - secure: fS7k5SMud75TI8dakhheaxUXgRt1e0DIAiB6z4bE61DoNPuDYC/jzsDVblbxfBjnTYyD+W2cQtHzK7CnqBB0F7oDQp3A+dgrp8dlYqC6TgB6WCnVJChJlJdA5AF4wwGcz1wu3Jj1tdH9mzZsYldBMSvPjLg2kV8E5qyfw2UDE3y9udFLkioW6m5XcbOrrSATAn9TDr3wbMKp4kafyk7jXlrriJlQLJDy1Luh2mIXKAgf9ntkSCCt86xctQ3etL4Bd8adhfuT9yjL4j56OI1uR8Simqqqycb0AGa5QBuIqOQmCeLGtnJAnLugcaXNUp1a1UfamTkoo1F2NQfyagwNeFvzxkqn9GXDz9e92tmxafrsWyGy5Tj5rIF9N1LaQYDsVoDOxgsovS2YmFDGBhWkG0moJErh8b8wjAwKdfxBEh710h3k9ka70KtrYsXqyWMIR2g81um2nioH0UFwxSKGZpdDu2SHRbzv2sQN1wX/9VU+fzjAa7B0xcrGXeblQmnxKpvFxmRXDVMwbXXaTWUsRFAi3tJRHR1gnxALNeEUW2vNqm7c/jOpUnHjM7NkaQa/pyL0lyQlEQJNZp9ZPPl9BV80jCx0mfBaAOjjs2msrQFP8wtFsLmOYt7rKLU1slI/Is8/Wwb7pqMANY2MZdpDtWyWl8aHXdtvrxhZkWKlvFY=
